services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./client
    command: npm run start
    volumes:
      - ./client/src/:/app/src/
    ports:
      - 8080:8080
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true=value
      - PORT=8080
